### ISSUE TITLE
Can't run locally

### ISSUE THREAD

**Issue by imskr** [Banno/webauthn#10]
**Your issue should cover only one concern.** If you wish to group issues or new features, please utilize Github's [milestone feature](https://github.com/Banno/webauthn/milestones).

## Summary

When running this locally, I am unable to register or login. No events happening. All I see is register and login buttons. Can you tell me the steps to run and test this locally? @eheikes

**Comment by eheikes** [comment]
Hi Shubham,

This project is a fork of the original [wallix project](https://github.com/wallix/webauthn) that was used to modify the server code for a private project. Have you tried using that project and do you run into the same problem with it?

**Comment by imskr** [comment]
Hi @eheikes, I've tried it and gives the same problem on client-side. Is it not implemented? All I see two buttons `register` and `login` which doesn't work

**Comment by eheikes** [comment]
It may not be. 😞  IIRC I tried it myself and ran into a similar problem.

The wallix project doesn't seem to have active development. This fork is also on hold and really just uses the server stuff. You might want to check out https://github.com/MasterKale/SimpleWebAuthn, which is new and I believe is designed to do the same thing. Good luck!

**Comment by imskr** [comment]
@eheikes Thanks!
